efnet_encoder:
  deepconvlstm:
    nb_conv_blocks: 2
    nb_filters: 64
    filter_width: 5
    batch_norm: False
    nb_layers_lstm: 2
    drop_prob: 0.5
    nb_units_lstm: 128
    dilation: 1
  
  # CNN + LSTM
  deepconvlstm_attn:
    nb_conv_blocks: 2
    nb_filters: 64
    filter_width: 5
    batch_norm: False
    nb_layers_lstm: 2
    drop_prob: 0.5
    nb_units_lstm: 128
    dilation: 1

  sa_har:
    nb_units: 128
    n_heads: 4
    dropout_rate: 0.2
    batch_norm: False

efnet_classifier:
    
  deepconvlstm_classifier:
    dropout_rate: 0.5
    hidden_dim: 64

  deepconvlstm_attn_classifier:
    dropout_rate: 0.5
    hidden_dim: 64
    
  sa_har_classifier:
    dropout_rate: 0.2