efnet_encoder:
  encoder_type: cnn
  
  cnn:
    kernel_size: 5
    conv_channels: [64, 128, 256]
    dropout_rate: 0.3
  
  lstm:
    hidden_size: 128
    num_layers: 2
    bidirectional: True
    dropout_rate: 0.3
    
  base_encoder:
    dropout_rate: 0.3

efnet_classifier:
  classifier_type: mlp
  
  mlp:
    classifier_hidden: [256, 128]  
    dropout_rate: 0.5
  
  base_classifier:
    dropout_rate: 0.5 