pamap2:
  source: https://archive.ics.uci.edu/ml/machine-learning-databases/00231/PAMAP2_Dataset.zip
  destination: pamap2.zip

  filename: "PAMAP2_Dataset/Protocol"
  sampling_freq: 33
  num_classes: 12
  num_channels: 9  # 가속도 센서만 사용 시 (x, y, z 축 × 3부위)
  # num_channels: 18  # 가속도+자이로 사용 시 (x, y, z 축 × 3부위 × 2센서)
  window_seconds: 5.12
  